# fly.toml app configuration file generated
# This file is NOT committed to version control
# Customize as needed

app = "sih-dr-backend"
primary_region = "iad"

[build]
  builder = "pacer"
  buildpacks = ["heroku/python"]

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[checks]
  [checks.alive]
    grace_period = "5s"
    interval = "30s"
    method = "get"
    timeout = "5s"
    type = "http"
    uri = "/api/"

[build.args]
  PYTHON_VERSION = "3.11"

[metrics]
  metrics_port = 9091

[processes]
  app = "gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 server:app"
